---
# Vagrant hostname and IP configuration.
vagrant_hostname: local.gatewaypeople.com
vagrant_ip: 192.168.4.40
vagrant_aliases:
  - "cf.local.gatewaypeople.com"
  - "local.xhprof.com"

# A list of synced folders, with the keys 'local_path', 'destination', and 'id'.
vagrant_synced_folders:
  - local_path: ~/Sites/gwayppl/docroot
    destination: /drupal
    id: drupal
    type: nfs

# Memory and CPU to use for this VM.
vagrant_memory: 2048
vagrant_cpus: 2

# Other variables in this file will be used during Ansible provisioning.
drush_version: "8.0.1"

firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "81"
  - "443"
  - "8025"
  - "8080"
  - "8443"
  - "8983"

varnish_listen_port: 80
varnish_storage: "malloc,256m"

apache_listen_port: 8080
apache_vhosts:
  - servername: "local.gatewaypeople.com"
    documentroot: "/drupal"
  - servername: "cf.local.gatewaypeople.com"
    documentroot: "/drupal"
  - servername: "local.xhprof.com"
    documentroot: "/usr/share/php/xhprof_html"

php_version: "5.6"
php_memory_limit: "1024M"
php_display_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/usr/sbin/ssmtp -t"

php_opcache_enabled_in_ini: true
php_opcache_conf_filename: 05-opcache.ini
php_opcache_memory_consumption: "128"

# Disable main XDebug components unless needed.
php_xdebug_coverage_enable: 0
php_xdebug_default_enable: 0
php_xdebug_remote_enable: 0

mysql_root_password: root
mysql_databases:
  - name: d7_gwp
    encoding: utf8
    collation: utf8_general_ci

solr_version: '3.6.2'

acquia_ssh_private_key: ~/.ssh/acquia_rsa
acquiacloud_aliases: ~/Downloads/acquiacloud.tar.gz
gwp_aliases: aliases.drushrc.php
